############################################################################
# apps/lvgl_demo/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = lvgl_demo
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192

CSRCS = lvgl_demo_main.c

include $(APPDIR)/Application.mk
